Areas/Admin/Pages/Users/ChangeEmail.cshtml.cs
using Markatooo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using NToastNotify;
using Markatooo.Data;
using System;
using Microsoft.EntityFrameworkCore;

namespace Markatooo.Areas.admin.Pages.Users
{
    [Authorize]
    public class ChangeEmailModel : PageModel
    {
        private readonly ApplicationDbContext applicationDb;
        private readonly UserManager<ApplicationUser> _userManger;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IToastNotification _toastNotification;
        [BindProperty]
        public ChangeEmailVM ChangeEmailVM { get; set; }
        public ChangeEmailModel(ApplicationDbContext applicationDb, UserManager<ApplicationUser> userManager, IToastNotification toastNotification, SignInManager<ApplicationUser> signInManager)
        {
            this.applicationDb = applicationDb;
            _userManger = userManager;
            _toastNotification = toastNotification;
            _signInManager = signInManager;
        }
        public void OnGet()
        {

        }
        //public async Task<IActionResult> OnPost()
        //{
        //    try
        //    {
        //        if (!ModelState.IsValid)
        //            return Page();
        //        if (resetPasswordModel.ConfirmPassword != resetPasswordModel.NewPassword)
        //        {
        //            _toastNotification.AddErrorToastMessage("Password not matched");
        //        }
        //        var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
        //        var user = await _userManager.FindByIdAsync(userid);
        //        var Result = await _userManager.ChangePasswordAsync(user, resetPasswordModel.CurrentPassword, resetPasswordModel.NewPassword);
        //        if (!Result.Succeeded)
        //        {
        //            foreach (var error in Result.Errors)
        //            {
        //                ModelState.TryAddModelError("", error.Description);
        //            }
        //            return Page();

        //        }
        //        _toastNotification.AddSuccessToastMessage("Password Updated Successfully");


        //    }
        //    catch (Exception)
        //    {
        //        _toastNotification.AddErrorToastMessage("Something went Error");
        //    }
        //    return RedirectToPage("../Login");
        //}

        public async Task<IActionResult> OnPost()
        {
            try
            {


                if (!ModelState.IsValid)
                    return Page();
                var user = await _userManger.GetUserAsync(User);
                user.UserName = ChangeEmailVM.NewEmail;
                user.Email = ChangeEmailVM.NewEmail;
                await _userManger.UpdateAsync(user);
                applicationDb.Attach(user).State = EntityState.Modified;
                applicationDb.SaveChanges();
                await _signInManager.RefreshSignInAsync(user);
                _toastNotification.AddSuccessToastMessage("Email Updated Successfully");
                return RedirectToPage("../../Index");
            }
            catch (Exception)
            {

                _toastNotification.AddErrorToastMessage("Something Went Error");
                return RedirectToPage("../../Index");
            }
        }
    }
}

Areas/Admin/Pages/Users/CreateLink.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Markatooo.Areas.Admin.Pages.Users
{
    public class CreateLinkModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Areas/Admin/Pages/Users/EditProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Markatooo.Data;
using Markatooo.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using NToastNotify;

namespace Markatooo.Areas.Admin.Pages.Users
{
    public class EditProfileModel : PageModel
    {
        public UserManager<ApplicationUser> usermanager;
        private readonly IToastNotification toastNotification;
        private readonly IWebHostEnvironment hostEnvironment;

        public SignInManager<ApplicationUser> SignInManager { get; }
        public ApplicationDbContext ApplicationDb { get; }

        public EditProfileModel(UserManager<ApplicationUser> usermanager, SignInManager<ApplicationUser> signInManager,IToastNotification _toastNotification,ApplicationDbContext applicationDb, IWebHostEnvironment _hostEnvironment)
        {
            this.usermanager = usermanager;
            SignInManager = signInManager;
            toastNotification = _toastNotification;
            ApplicationDb = applicationDb;
            hostEnvironment = _hostEnvironment;
        }
        [BindProperty]
        public ProfileVM ProfileVM { get; set; }


        public async Task<IActionResult> OnPostChangepassword()
        {
            var user = await usermanager.GetUserAsync(User);
            var result = await usermanager.ChangePasswordAsync(user, ProfileVM.CurrentPassword, ProfileVM.NewPassword);
            if (!result.Succeeded)
            {
                toastNotification.AddErrorToastMessage("Something Went Error..");
                return Page();
            }
            user.LastChangePassword = DateTime.Now.Date;
            ApplicationDb.Attach(user).State = EntityState.Modified;
            ApplicationDb.SaveChanges();
            await SignInManager.RefreshSignInAsync(user);
            toastNotification.AddSuccessToastMessage("Password Updated Successfully");
            return Page();

        }
        public async Task<IActionResult> OnPostChangeEmail()
        {
            var user = await usermanager.GetUserAsync(User);
            user.UserName = ProfileVM.NewEmail;
            user.Email = ProfileVM.NewEmail;
            await usermanager.UpdateAsync(user);
            ApplicationDb.Attach(user).State = EntityState.Modified;
            ApplicationDb.SaveChanges();
            await SignInManager.RefreshSignInAsync(user);
            toastNotification.AddSuccessToastMessage("Email Updated Successfully");
            return Page();
        }
        public async Task<IActionResult> OnPost(IFormFile file)
        {
            var user = await usermanager.GetUserAsync(User);
            if (file != null)
            {
                if (ProfileVM.photo != null)
                {
                    var ImagePath = Path.Combine(hostEnvironment.WebRootPath, user.Photo);
                    if (System.IO.File.Exists(ImagePath))
                    {
                        System.IO.File.Delete(ImagePath);
                    }
                }
                string folder = "Images/Profile/";
                user.Photo = await UploadImage(folder, file);
            }
            await usermanager.UpdateAsync(user);
            ApplicationDb.Attach(user).State = EntityState.Modified;
            ApplicationDb.SaveChanges();
            return Page();
        }
        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(hostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return folderPath;
        }
    }
}

Pages/Createlink.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using NToastNotify;
using Markatooo.Data;
using Markatooo.Models;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using QRCoder;
using System.Drawing;

namespace Markatooo.Areas.Admin.Pages.Customer
{
    public class CreatelinkModel : PageModel
    {
        private MarkatoooContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IToastNotification _toastNotification;
        [BindProperty]
        public PaymentModel model { get; set; }
        public HttpClient httpClient { get; set; }
        public CreatelinkModel(MarkatoooContext context, IWebHostEnvironment hostEnvironment, IToastNotification toastNotification, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _toastNotification = toastNotification;
            UserManager = userManager;
            httpClient = new HttpClient();
            model = new PaymentModel();
        }
        [BindProperty(SupportsGet = true)]
        public bool ArLang { get; set; }
        public string QRScan { get; set; }


        public UserManager<ApplicationUser> UserManager { get; }
        public void OnGet()
        {
          
        }
        public async Task<IActionResult> OnPost(IFormFile file)
        {
            
            try
            {
                if (file != null)
                {
                    string folder = "Attachment/";
                    model.Attachment = await UploadImage(folder, file);
                }
                var payments = _context.Payments.Include(a => a.PaymentStatus).Where(a => a.PaymentStatusId == 2).Select(a => a.OrderNumber).ToList();
                if (payments.Contains(model.OrderNumber) == true)
                {
                    _toastNotification.AddWarningToastMessage("order number exists...");
                    return Page();
                }
                model.Active = true;
                //model.issuccess = false;
                model.PaymentStatusId = 1;
                model.TransactionDate = DateTime.Now;
                // model.estimatedtime = DateTime.Now.AddDays(1);
                _context.Payments.Add(model);
                _context.SaveChanges();
               
              
            }
            catch (Exception e)
            {
                _toastNotification.AddErrorToastMessage("Something went wrong");
                return Page();
            }
            return RedirectToPage("Pay_Customer", new { paymentid = model.PaymentModelId });
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_hostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return folderPath;
        }

    }
}

Areas/Admin/Pages/Users/ChangeEmail.cshtml
@page
@model Markatooo.Areas.admin.Pages.Users.ChangeEmailModel
@using DevExtreme.AspNet.Mvc
@{
    Layout = "~/Pages/Shared/_MainLayout.cshtml";

}
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h2 class="card-header d-flex justify-content-between align-items-center">
                            @sharedResource["Change Email"]
                        </h2>
                    </div>
                    <div class="card-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <br />
                        <form id="form" method="post">
                            @(Html.DevExtreme().Form<Markatooo.ViewModel.ChangeEmailVM>()
        .FormData(Model.ChangeEmailVM)
        .Items(items =>
        {


            items.AddSimpleFor(m => m.NewEmail).IsRequired(true).Label(k => k.Text(sharedResource["New Email"])).Editor(e => e.TextBox().Mode(TextBoxMode.Email));
            items.AddSimpleFor(m => m.ConfirmNewEmail).IsRequired(true).Label(k => k.Text(sharedResource["Confirm Email"])).Editor(e => e.TextBox().Mode(TextBoxMode.Email));

            items.AddButton()
                        .ColSpan(3)
                        .HorizontalAlignment(HorizontalAlignment.Right)
                        .ButtonOptions(b => b.Text(sharedResource["Save"])
                        .Type(ButtonType.Success)
                        .UseSubmitBehavior(true)).CssClass("invers");
        })
)
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("NToastNotify")

Areas/Admin/Pages/Users/CreateLink.cshtml
@page
@model Markatooo.Areas.Admin.Pages.Users.CreateLinkModel
@{
}

Areas/Admin/Pages/Users/EditProfile.cshtml
@page
@model Markatooo.Areas.Admin.Pages.Users.EditProfileModel
@using Microsoft.AspNetCore.Identity
@using Markatooo.Data
@inject UserManager<ApplicationUser> usermanager
@{
    Layout = "~/Pages/Shared/_TemplateLayout.cshtml";
    var user = await usermanager.GetUserAsync(User);

}
<!-- Secondary Menu
 ============================================= -->
<div class="bg-primary">
    <div class="container d-flex justify-content-center">
        <ul class="nav nav-pills alternate nav-lg border-bottom-0">
            <li class="nav-item"> <a class="nav-link" >@sharedResource["Account"]</a></li>
            @*<li class="nav-item"> <a class="nav-link active" href="settings-security.html">Security</a></li>
                <li class="nav-item"> <a class="nav-link" href="settings-payment-methods.html">Payment Methods</a></li>
                <li class="nav-item"> <a class="nav-link" href="settings-notifications.html">Notifications</a></li>*@
        </ul>
    </div>
</div>
<!-- Secondary Menu end -->
<!-- Content
============================================= -->
<div id="content" class="py-4">
    <div class="container">
        <div class="row">
                <!-- Left Panel
    ============================================= -->
            <aside class="col-lg-3">
                <form method="post" enctype="multipart/form-data">


                    <!-- Profile Details
    =============================== -->
                    <div class="bg-white shadow-sm rounded text-center p-3 mb-4">
                        <div class="profile-thumb mt-3 mb-4">
                            @if (user.Photo == null)
                            {
                                <img class="rounded-circle" style="max-width: 100%;height:100%" src="~/Profile-Icon.png" alt="">
                            }
                            else
                            {
                                <img class="rounded-circle" style="max-width: 100%; height: 100%" src="~/@user.Photo" alt="">
                            }

                            <div class="profile-thumb-edit bg-primary text-white" data-bs-toggle="tooltip" title="@sharedResource[""]Change Profile Picture">
                                <i class="fas fa-camera position-absolute"></i>
                                <input type="file" name="file" class="custom-file-input" id="customFile">
                            </div>

                        </div>
                        <p class="text-3 fw-500 mb-2">@sharedResource["Hello"], @user.Email</p>
                        <p class="mb-2"><button type="submit" style="background:transparent;border:none" href="settings-profile.html" class="text-5 text-light" data-bs-toggle="tooltip" title="@sharedResource["Edit Profile Photo"]"><i class="fas fa-edit"></i></button></p>

                    </div>
                    <!-- Profile Details End -->
                    <!-- Available Balance
    =============================== -->
                    <!--<div class="bg-white shadow-sm rounded text-center p-3 mb-4">
                        <div class="text-17 text-light my-3"><i class="fas fa-wallet"></i></div>
                        <h3 class="text-9 fw-400">$2956.00</h3>
                        <p class="mb-2 text-muted opacity-8">Available Balance</p>
                        <hr class="mx-n3">
                        <div class="d-flex"><a href="withdraw-money.html" class="btn-link me-auto">Withdraw</a> <a href="deposit-money.html" class="btn-link ms-auto">Deposit</a></div>
                    </div>-->
                    <!-- Available Balance End -->
                    <!-- Need Help?
    =============================== -->
                    <!--<div class="bg-white shadow-sm rounded text-center p-3 mb-4">
                        <div class="text-17 text-light my-3"><i class="fas fa-comments"></i></div>
                        <h3 class="text-5 fw-400 my-4">Need Help?</h3>
                        <p class="text-muted opacity-8 mb-4">
                            Have questions or concerns regrading your account?<br>
                            Our experts are here to help!.
                        </p>
                        <div class="d-grid"><a href="#" class="btn btn-primary">Chate with Us</a></div>
                    </div>-->
                </form>
                    <!-- Need Help? End -->
            </aside>
           
        <!-- Left Panel End -->
        <!-- Middle Panel
        ============================================= -->
        <div class="col-lg-9">

            <!-- Password
            ============================================= -->
            <div class="bg-white shadow-sm rounded p-4 mb-4">
                <h3 class="text-5 fw-400 d-flex align-items-center mb-4">@sharedResource["Password"]<a href="#change-password" data-bs-toggle="modal" class="ms-auto text-2 text-uppercase btn-link"><span class="me-1"><i class="fas fa-edit"></i></span>@sharedResource["Change"]</a></h3>
                <hr class="mx-n4 mb-4">
                <p class="text-3">@sharedResource["Update your password"]. - <span class="text-muted">@sharedResource["Last changed"]:@user.LastChangePassword.Date.ToString("dd,MMMM,yyyy")  </span></p>
            </div>
            <!-- Edit Details Modal
            ================================== -->
            <div id="change-password" class="modal fade " role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title fw-400">@sharedResource["Change Password"]</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body p-4">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <form id="changePassword" asp-page-handler="Changepassword" method="post">
                                <div class="mb-3">
                                    <label for="existingPassword" class="form-label">@sharedResource["Current Password"]</label>
                                    <input type="text" class="form-control" asp-for="@Model.ProfileVM.CurrentPassword" data-bv-field="existingpassword" id="existingPassword" required placeholder="@sharedResource["Enter Current Password"]">
                                    <span asp-validation-for="@Model.ProfileVM.CurrentPassword" class="text-danger"></span>
                                </div>
                                <div class="mb-3">
                                    <label for="newPassword" class="form-label">@sharedResource["New Password"]</label>
                                    <input type="text" class="form-control" asp-for="@Model.ProfileVM.NewPassword" data-bv-field="newpassword" id="newPassword" required placeholder="@sharedResource["Enter New Password"]">
                                    <span asp-validation-for="@Model.ProfileVM.NewPassword" class="text-danger"></span>
                                </div>
                                <div class="mb-3">
                                    <label for="confirmPassword" class="form-label">@sharedResource["Confirm New Password"]</label>
                                    <input type="text" class="form-control" asp-for="@Model.ProfileVM.ConfirmNewPassword" data-bv-field="confirmgpassword" id="confirmPassword" required placeholder="@sharedResource["Enter Confirm New Password"]">
                                    <span asp-validation-for="@Model.ProfileVM.ConfirmNewPassword" class="text-danger"></span>

                                </div>
                                <div class="d-grid mt-4"><button class="btn btn-primary" type="submit">@sharedResource["Update Password"]</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


            <div class="bg-white shadow-sm rounded p-4 mb-4">
                <h3 class="text-5 fw-400 d-flex align-items-center mb-4">@sharedResource["Email"]<a href="#change-Email" data-bs-toggle="modal" class="ms-auto text-2 text-uppercase btn-link"><span class="me-1"><i class="fas fa-edit"></i></span>@sharedResource["Change"]</a></h3>
                <hr class="mx-n4 mb-4">
                <p class="text-3">@user.Email . <span class="text-muted"></span></p>
            </div>

            <div id="change-Email" class="modal fade " role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title fw-400">@sharedResource["Change Email"]</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body p-4">
                            <form id="changeEmail" asp-page-handler="ChangeEmail" method="post">
                                <div class="mb-3">
                                    <label for="newEmail" class="form-label">@sharedResource["New Email"]</label>
                                    <input type="text" class="form-control" asp-for="@Model.ProfileVM.NewEmail" data-bv-field="newEmail" id="newEmail" required placeholder="@sharedResource["Enter New Email"]">
                                    <span asp-validation-for="@Model.ProfileVM.NewEmail" class="text-danger"></span>
                                </div>
                                <div class="mb-3">
                                    <label for="confirmEmail" class="form-label">@sharedResource["Confirm New Email"]</label>
                                    <input type="text" class="form-control" asp-for="@Model.ProfileVM.ConfirmNewEmail" data-bv-field="confirmEmail" id="confirmEmail" required placeholder="@sharedResource["Enter Confirm New Email"]">
                                    <span asp-validation-for="@Model.ProfileVM.ConfirmNewEmail" class="text-danger"></span>
                                </div>
                                <div class="d-grid mt-4"><button class="btn btn-primary" type="submit">@sharedResource["Update Email"]</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>





        <!-- Middle Panel End -->
    </div>
</div>
</div>
@await Component.InvokeAsync("NToastNotify")
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}